create table if not exists public.inventory_managed_products (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  product_id bigint not null references public.products(id),
  receiver text not null default '',
  display_order integer not null default 0,
  del_yn text not null default 'N',
  updated_by text not null default ''
);

create table if not exists public.inventory_weekly_records (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  product_id bigint not null references public.products(id),
  week_start_date date not null,
  available_box_override numeric null,
  proper_stock_box numeric null,
  production_date_note text not null default '',
  production_plan_note text not null default '',
  del_yn text not null default 'N',
  updated_by text not null default ''
);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'inventory_managed_products_del_yn_check'
  ) then
    alter table public.inventory_managed_products
      add constraint inventory_managed_products_del_yn_check
      check (del_yn in ('Y', 'N'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'inventory_weekly_records_del_yn_check'
  ) then
    alter table public.inventory_weekly_records
      add constraint inventory_weekly_records_del_yn_check
      check (del_yn in ('Y', 'N'));
  end if;
end
$$;

create unique index if not exists uq_inventory_managed_products_active_product
  on public.inventory_managed_products (product_id)
  where del_yn = 'N';

create unique index if not exists uq_inventory_weekly_records_active_product_week
  on public.inventory_weekly_records (product_id, week_start_date)
  where del_yn = 'N';

create index if not exists idx_inventory_managed_products_receiver
  on public.inventory_managed_products (receiver);

create index if not exists idx_inventory_managed_products_del_yn
  on public.inventory_managed_products (del_yn);

create index if not exists idx_inventory_weekly_records_week
  on public.inventory_weekly_records (week_start_date);

create index if not exists idx_inventory_weekly_records_product
  on public.inventory_weekly_records (product_id);

create index if not exists idx_inventory_weekly_records_del_yn
  on public.inventory_weekly_records (del_yn);

alter table public.inventory_managed_products enable row level security;
alter table public.inventory_weekly_records enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'inventory_managed_products'
      and policyname = 'inventory_managed_products_select_anon'
  ) then
    create policy inventory_managed_products_select_anon
      on public.inventory_managed_products for select to anon using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'inventory_managed_products'
      and policyname = 'inventory_managed_products_insert_anon'
  ) then
    create policy inventory_managed_products_insert_anon
      on public.inventory_managed_products for insert to anon with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'inventory_managed_products'
      and policyname = 'inventory_managed_products_update_anon'
  ) then
    create policy inventory_managed_products_update_anon
      on public.inventory_managed_products for update to anon using (true) with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'inventory_managed_products'
      and policyname = 'inventory_managed_products_delete_anon'
  ) then
    create policy inventory_managed_products_delete_anon
      on public.inventory_managed_products for delete to anon using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'inventory_weekly_records'
      and policyname = 'inventory_weekly_records_select_anon'
  ) then
    create policy inventory_weekly_records_select_anon
      on public.inventory_weekly_records for select to anon using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'inventory_weekly_records'
      and policyname = 'inventory_weekly_records_insert_anon'
  ) then
    create policy inventory_weekly_records_insert_anon
      on public.inventory_weekly_records for insert to anon with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'inventory_weekly_records'
      and policyname = 'inventory_weekly_records_update_anon'
  ) then
    create policy inventory_weekly_records_update_anon
      on public.inventory_weekly_records for update to anon using (true) with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'inventory_weekly_records'
      and policyname = 'inventory_weekly_records_delete_anon'
  ) then
    create policy inventory_weekly_records_delete_anon
      on public.inventory_weekly_records for delete to anon using (true);
  end if;
end
$$;
